import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../core/theme/app_theme.dart';
import '../../core/widgets/app_widgets.dart';
import '../../providers/app_auth_provider.dart' as app;
import '../../services/venues_service.dart';

class BusinessSettingsScreen extends StatefulWidget { const BusinessSettingsScreen({super.key}); @override State<BusinessSettingsScreen> createState() => _BusinessSettingsScreenState(); }
class _BusinessSettingsScreenState extends State<BusinessSettingsScreen> {
  final _name = TextEditingController(); final _type = TextEditingController(text: 'Banquet Hall'); final _address = TextEditingController(); final _city = TextEditingController(); final _capacity = TextEditingController(); final _website = TextEditingController(); bool _loaded=false; bool _busy=false;
  @override void dispose(){ for(final c in [_name,_type,_address,_city,_capacity,_website]){c.dispose();} super.dispose();}
  Future<void> _load(String venueId) async { if(_loaded || venueId.isEmpty) return; final v=await VenuesService.getVenue(venueId); if(v==null || !mounted) return; setState((){_loaded=true; _name.text=v.name; _type.text=v.venueType; _address.text=v.streetAddress; _city.text=v.city; _capacity.text=v.capacity.toString(); _website.text=v.website ?? 'https://festalytics.com/venue/$venueId';});}
  Future<void> _save(String venueId) async { setState(()=>_busy=true); await VenuesService.saveVenue(venueId, {'name':_name.text.trim(),'hallName':_name.text.trim(),'venueType':_type.text.trim(),'streetAddress':_address.text.trim(),'city':_city.text.trim(),'capacity':int.tryParse(_capacity.text)??0,'website':_website.text.trim(),'categories':['BANQUET HALL','CATERING','DECOR']}); if(mounted){setState(()=>_busy=false); ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Business settings saved.'), backgroundColor: AppColors.success));}}
  @override Widget build(BuildContext context){ final venueId=context.watch<app.AppAuthProvider>().currentUser?.venueId??''; _load(venueId); return Scaffold(appBar: AppBar(title: const Text('Business Settings')), body: venueId.isEmpty? const EmptyState(icon: Icons.business, title: 'No business linked', subtitle: 'Vendor signup creates the venue document automatically.') : ListView(padding: const EdgeInsets.all(18), children:[const SectionTitle('Business profile', subtitle: 'Saved into venues document like web business settings.'), CandyCard(child: Column(children:[TextField(controller:_name, decoration: const InputDecoration(labelText:'Venue name')), const SizedBox(height:10), TextField(controller:_type, decoration: const InputDecoration(labelText:'Venue type')), const SizedBox(height:10), TextField(controller:_address, decoration: const InputDecoration(labelText:'Address')), const SizedBox(height:10), Row(children:[Expanded(child:TextField(controller:_city, decoration: const InputDecoration(labelText:'City'))), const SizedBox(width:8), Expanded(child:TextField(controller:_capacity, keyboardType: TextInputType.number, decoration: const InputDecoration(labelText:'Capacity')))]), const SizedBox(height:10), TextField(controller:_website, decoration: const InputDecoration(labelText:'Website')), const SizedBox(height:14), SizedBox(width: double.infinity, child: ElevatedButton(onPressed:_busy?null:()=>_save(venueId), child: Text(_busy?'Saving...':'Save business')))]))]));}
}
