import 'package:flutter/material.dart';
import '../../core/theme/app_theme.dart';
import '../../core/widgets/app_widgets.dart';

class HelpSettingsScreen extends StatelessWidget { const HelpSettingsScreen({super.key}); @override Widget build(BuildContext context)=>const _StaticSettings(title:'Help & Support', icon:Icons.help_outline, lines:['Contact Festalytics support','Read vendor onboarding guide','Report booking/payment issues','Request feature help']); }
class NotificationsSettingsScreen extends StatelessWidget { const NotificationsSettingsScreen({super.key}); @override Widget build(BuildContext context)=>const _StaticSettings(title:'Notifications', icon:Icons.notifications_none, lines:['Booking updates','Quotation alerts','Borrow Hub updates','Customer messages']); }
class PaymentsSettingsScreen extends StatelessWidget { const PaymentsSettingsScreen({super.key}); @override Widget build(BuildContext context)=>const _StaticSettings(title:'Payments', icon:Icons.payments_outlined, lines:['Bank account setup','Advance payment tracking','Invoice settings','Payout history']); }
class SecuritySettingsScreen extends StatelessWidget { const SecuritySettingsScreen({super.key}); @override Widget build(BuildContext context)=>const _StaticSettings(title:'Security', icon:Icons.security_outlined, lines:['Change password from Firebase email reset','Enable verified email','Review active role and account status','Keep API secrets on backend only']); }
class _StaticSettings extends StatelessWidget { final String title; final IconData icon; final List<String> lines; const _StaticSettings({required this.title, required this.icon, required this.lines}); @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:Text(title)), body:ListView(padding:const EdgeInsets.all(18), children:[CandyCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start, children:[Icon(icon,color:AppColors.primary,size:42), const SizedBox(height:12), Text(title, style:const TextStyle(fontSize:22,fontWeight:FontWeight.w900)), const SizedBox(height:8), const Text('Mobile equivalent of the corresponding web settings page.', style: TextStyle(color:AppColors.muted))])), const SizedBox(height:14), ...lines.map((l)=>Padding(padding:const EdgeInsets.only(bottom:10), child:CandyCard(child:Row(children:[const Icon(Icons.check_circle_outline,color:AppColors.primary), const SizedBox(width:10), Expanded(child:Text(l))]))))])); }
